# Application Name & Port Configuration
spring.application.name=rediscachedapi
server.port=8080

# 1. Database Connection URL
# Points to localhost:3306 and connects to the 'mystudentdb' database created in docker-compose.
spring.datasource.url=${DB_URL}

# 2. Database Credentials
# Matches the environment variables set in docker-compose (MYSQL_ROOT_PASSWORD=password)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 3. MySQL JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Options: 'update' (modifies schema automatically), 'create' (recreates schema on boot), 'none'
spring.jpa.hibernate.ddl-auto=update

# 5. SQL Query Logging (Useful for Development/Debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
logging.level.org.springframework.cache=TRACE